from os import environ as env

ATTESTATION_QUEUE_NAME = 'ATTESTATION_REQUESTS'

VERIFICATION_QUEUE_NAME = 'VERIFICATION_REQUESTS'

RABBITMQ_HOST = env.get('DVA_RABBITMQ_HOST', default='localhost')

LOG_LEVEL = env.get('DVA_LOG_LEVEL', default='info')
