<template>
  <article class="card">
    <div class="card-header"><div class="card-mark"><v-icon name="fa-user-shield" /></div><div class="header-copy"><span>Verification attempt</span><h3>{{ pres.id || pres.thread_id || 'Verification' }}</h3></div><span class="status" :class="record.failure.status === 'passed' ? 'pass' : 'fail'"><i></i>{{ record.failure.status === 'passed' ? 'Verified' : 'Needs attention' }}</span></div>
    <div class="card-body"><div class="field-grid"><div class="field"><span><v-icon name="fa-certificate" /> Credential</span><strong>{{ request.credential_id || 'Not available' }}</strong></div><div class="field"><span><v-icon name="fa-file-signature" /> VLA</span><strong>{{ response.vla_id || request.vla_id || 'Not available' }}</strong></div><div class="field"><span><v-icon name="fa-database" /> Data commitment</span><strong>{{ response.data_hash || request.data_hash || 'Not available' }}</strong></div><div class="field"><span><v-icon name="fa-user-cog" /> Result</span><strong>{{ record.failure.code || 'PASS' }}</strong></div></div><div class="meta-row"><span><v-icon name="fa-calendar-alt" /> Checked {{ formatDate(pres.created_at) }}</span></div><FailureExplanation v-if="record.failure.status !== 'passed'" :failure="record.failure" heading="Why this verification needs attention" /><button class="expand-button" @click="expanded = !expanded"><v-icon :name="expanded ? 'fa-chevron-up' : 'fa-chevron-down'" /> {{ expanded ? 'Hide details' : 'Show audit details' }}</button><div v-if="expanded"><div class="section-title"><v-icon name="fa-code" /> Request</div><vue-json-pretty :data="request" :deep="2" :virtual="true" :height="130" /><div class="section-title"><v-icon name="fa-code" /> Response</div><vue-json-pretty :data="response" :deep="2" :virtual="true" :height="130" /></div></div>
  </article>
</template>
<script setup>
import { computed, ref } from 'vue'
import VueJsonPretty from 'vue-json-pretty'
import 'vue-json-pretty/lib/styles.css'
import FailureExplanation from './FailureExplanation.vue'
import { normalizeVerificationRecord } from '../failures/failureModel.js'
const props=defineProps({pres:{type:Object,required:true}})
const expanded=ref(false)
const record = computed(() => normalizeVerificationRecord(props.pres))
const request=computed(()=>props.pres?.request||{})
const response=computed(()=>props.pres?.response||{})
function formatDate(v){return v?new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'—'}
</script>
<style scoped>
.card{display:flex;flex-direction:column;height:100%;overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff;box-shadow:0 4px 18px rgba(15,23,42,.045);transition:transform .16s,box-shadow .16s}.card:hover{transform:translateY(-2px);box-shadow:0 10px 26px rgba(15,23,42,.09)}.card-header{display:flex;align-items:center;gap:11px;padding:16px;color:#fff;background:#0e7490}.card-mark{display:grid;place-items:center;width:37px;height:37px;border-radius:10px;color:#cffafe;background:rgba(255,255,255,.15);font-size:.95rem}.header-copy{min-width:0;flex:1}.header-copy span{display:block;color:#cffafe;font-size:.62rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.header-copy h3{overflow:hidden;margin:4px 0 0;font-size:.82rem;text-overflow:ellipsis;white-space:nowrap}.status{display:inline-flex;align-items:center;gap:5px;padding:5px 7px;border-radius:999px;font-size:.62rem;font-weight:800}.status i{width:6px;height:6px;border-radius:50%}.status.pass{color:#166534;background:#dcfce7}.status.pass i{background:#22c55e}.status.fail{color:#991b1b;background:#fee2e2}.status.fail i{background:#ef4444}.card-body{display:flex;flex:1;flex-direction:column;padding:16px}.field-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.field{min-width:0;padding:10px;border:1px solid #f1f5f9;border-radius:9px;background:#f8fafc}.field span{display:flex;align-items:center;gap:5px;color:#94a3b8;font-size:.65rem}.field span svg{color:#0891b2}.field strong,.credential-line strong{display:block;overflow:hidden;margin-top:5px;color:#475569;font-size:.7rem;text-overflow:ellipsis;white-space:nowrap}.meta-row{display:flex;justify-content:space-between;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid #f1f5f9;color:#64748b;font-size:.65rem}.meta-row span:first-child{display:flex;align-items:center;gap:5px}.meta-row svg{color:#0891b2}.section-title{display:flex;align-items:center;gap:6px;margin:14px 0 7px;padding-top:12px;border-top:1px solid #f1f5f9;color:#475569;font-size:.7rem;font-weight:800}.section-title svg{color:#0891b2}.credential-line{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #f8fafc}.credential-line span{color:#94a3b8;font-size:.65rem}.card-body :deep(.vjs-tree){font-size:.68rem}@media(max-width:420px){.field-grid{grid-template-columns:1fr}.meta-row{flex-direction:column}}
.expand-button{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;margin-top:14px;padding:8px;border:1px solid #bae6fd;border-radius:8px;color:#0e7490;background:#f0f9ff;font-size:.7rem;font-weight:800;cursor:pointer}.expand-button:hover{background:#e0f2fe}
.status.pending{color:#92400e;background:#fef3c7}.status.pending i{background:#f59e0b}
@media(max-width:760px){.card:hover{transform:none}.card-header{padding:14px}.card-body{padding:14px}.field strong{white-space:normal;overflow-wrap:anywhere}.meta-row{flex-wrap:wrap}.meta-row span:first-child{white-space:normal;overflow-wrap:anywhere}}
</style>
