<template>
  <article class="card">
    <div class="card-header"><div class="card-mark"><v-icon name="fa-stamp" /></div><div class="header-copy"><span>Veracity event</span><h3>{{ req.vla?.name || 'Attestation request' }}</h3></div><span class="status" :class="state"><i></i>{{ stateLabel }}</span></div>
    <div class="card-body"><p v-if="req.vla?.description" class="description">{{ req.vla.description }}</p><div class="field-grid"><div class="field"><span><v-icon name="fa-people-arrows" /> Exchange</span><strong>{{ req.exchangeID || '—' }}</strong></div><div class="field"><span><v-icon name="fa-file-signature" /> Contract</span><strong>{{ req.contractID || '—' }}</strong></div><div class="field"><span><v-icon name="fa-user" /> Attester</span><strong>{{ req.attesterID || '—' }}</strong></div><div class="field"><span><v-icon name="fa-clock" /> Received</span><strong>{{ formatDate(req.receivedDate) }}</strong></div></div><div v-if="req.vla?.tags?.length" class="tags"><span v-for="tag in req.vla.tags" :key="tag">{{ tag }}</span></div><div class="meta-row"><span><v-icon name="fa-certificate" /> {{ req.vcID || 'Credential not issued' }}</span><span>{{ req.type === 'pov' ? 'Proof' : 'Attestation' }}</span></div><button class="expand-button" @click="expanded = !expanded"><v-icon :name="expanded ? 'fa-chevron-up' : 'fa-chevron-down'" /> {{ expanded ? 'Hide details' : 'Show data and evaluation' }}</button><div v-if="expanded"><div class="section-title"><v-icon name="fa-database" /> Data</div><vue-json-pretty :data="req.data" :deep="2" :virtual="true" :height="100" /><div class="section-title"><v-icon name="fa-chart-line" /> Evaluation results</div><vue-json-pretty :data="evaluationResults" :deep="2" :virtual="true" :height="150" /></div></div>
  </article>
</template>
<script setup>
import { computed, ref } from 'vue'
import VueJsonPretty from 'vue-json-pretty'
import 'vue-json-pretty/lib/styles.css'
const props=defineProps({req:{type:Object,required:true}})
const expanded=ref(false)
const state = computed(() => props.req.evaluationDate ? (props.req.evaluationPassing === true ? 'pass' : 'fail') : 'pending')
const stateLabel = computed(() => ({ pass: 'Passed', fail: 'Failed', pending: 'Pending' })[state.value])
const evaluationResults=computed(()=>{try{return props.req.evaluationResults?JSON.parse(props.req.evaluationResults):{status:'Pending'}}catch{return {status:'Unavailable'}}})
function formatDate(v){return v?new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'—'}
</script>
<style scoped>
.card{display:flex;flex-direction:column;height:100%;overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff;box-shadow:0 4px 18px rgba(15,23,42,.045);transition:transform .16s,box-shadow .16s}.card:hover{transform:translateY(-2px);box-shadow:0 10px 26px rgba(15,23,42,.09)}.card-header{display:flex;align-items:center;gap:11px;padding:16px;color:#fff;background:#0e7490}.card-mark{display:grid;place-items:center;width:37px;height:37px;border-radius:10px;color:#cffafe;background:rgba(255,255,255,.15);font-size:.95rem}.header-copy{min-width:0;flex:1}.header-copy span{display:block;color:#cffafe;font-size:.62rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.header-copy h3{overflow:hidden;margin:4px 0 0;font-size:.82rem;text-overflow:ellipsis;white-space:nowrap}.status{display:inline-flex;align-items:center;gap:5px;padding:5px 7px;border-radius:999px;font-size:.62rem;font-weight:800}.status i{width:6px;height:6px;border-radius:50%}.status.pass{color:#166534;background:#dcfce7}.status.pass i{background:#22c55e}.status.fail{color:#991b1b;background:#fee2e2}.status.fail i{background:#ef4444}.card-body{display:flex;flex:1;flex-direction:column;padding:16px}.description{margin:0 0 14px;color:#64748b;font-size:.72rem;line-height:1.45}.field-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.field{min-width:0;padding:10px;border:1px solid #f1f5f9;border-radius:9px;background:#f8fafc}.field span{display:flex;align-items:center;gap:5px;color:#94a3b8;font-size:.65rem}.field span svg{color:#0891b2}.field strong{display:block;overflow:hidden;margin-top:5px;color:#475569;font-size:.7rem;text-overflow:ellipsis;white-space:nowrap}.tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:12px}.tags span{padding:4px 7px;border-radius:999px;color:#0e7490;background:#ecfeff;font-size:.62rem;font-weight:700}.meta-row{display:flex;justify-content:space-between;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid #f1f5f9;color:#64748b;font-size:.65rem}.meta-row span:first-child{display:flex;gap:5px;overflow:hidden;align-items:center;text-overflow:ellipsis;white-space:nowrap}.meta-row svg{color:#0891b2}.section-title{display:flex;align-items:center;gap:6px;margin:14px 0 7px;padding-top:12px;border-top:1px solid #f1f5f9;color:#475569;font-size:.7rem;font-weight:800}.section-title svg{color:#0891b2}.card-body :deep(.vjs-tree){font-size:.68rem}@media(max-width:420px){.field-grid{grid-template-columns:1fr}}
.expand-button{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;margin-top:14px;padding:8px;border:1px solid #bae6fd;border-radius:8px;color:#0e7490;background:#f0f9ff;font-size:.7rem;font-weight:800;cursor:pointer}.expand-button:hover{background:#e0f2fe}
.status.pending{color:#92400e;background:#fef3c7}.status.pending i{background:#f59e0b}
</style>
