ktor:
  deployment:
    port: 9090
  application:
    modules:
      - hu.bme.mit.ftsrg.dva.api.ApplicationKt.module

swagger:
  openapiFile: "$DVA_OPENAPI_FILE:../docs/spec/openapi.yaml"

rabbitmq:
  host: "$DVA_RABBITMQ_HOST:localhost"

acaPy:
  agent:
    url: "$DVA_ACA_PY_AGENT_URL:http://localhost:8030"
  controller:
    url: "$DVA_ACA_PY_CONTROLLER_URL:http://localhost:8050"