ktor:
  deployment:
    port: 9090
  application:
    modules:
      - hu.bme.mit.ftsrg.dva.api.ApplicationKt.module

swagger:
  openapiFile: "$DVA_OPENAPI_FILE:../docs/spec/openapi.yaml"

postgres:
  url: "$DVA_POSTGRES_URL:postgresql://localhost:5432/dva"
  user: "$DVA_POSTGRES_USER:postgres"
  password: "$DVA_POSTGRES_PASSWORD:postgres"

processing:
  url: "$DVA_PROCESSING_URL:http://localhost:5000"

vlaManager:
  url: "$DVA_VLA_MANAGER_URL:http://localhost:8000"

vcManager:
  url: "$DVA_VC_MANAGER_URL:http://localhost:8000"

dva:
  apiKey: "$DVA_API_KEY:"