import os


ADMIN_URL = os.getenv("ADMIN_URL")
ADMIN_LABEL = os.getenv("ADMIN_LABEL")

PEER_AGENT_URL = os.getenv("PEER_AGENT_URL")
PEER_CONTROLLER_URL = os.getenv("PEER_CONTROLLER_URL")
PEER_CONTROLLER_PORT_IN = os.getenv("PEER_CONTROLLER_PORT_IN")
PEER_CONTROLLER_PORT_OUT = os.getenv("PEER_CONTROLLER_PORT_OUT")
PEER_LABEL = os.getenv("PEER_LABEL")

LOG_FILE = "log.json"
