---
services:

  karate:
    build: karate/
    volumes:
      - ./features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./reports:/app/target/karate-reports
    command: ./features/
    depends_on:
      dva-api:
        condition: service_healthy

  dva-api:
    build:
      context: ../
      dockerfile: ./dva-jvm/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit
    command: api
    ports: [9090:9090]
    healthcheck:
      test: nc -z localhost 9090
      interval: 15s
      timeout: 30s
      retries: 3

    depends_on:
      rabbit:
        condition: service_healthy

  dva-python:
    build:
      context: ../
      dockerfile: ./dva-python/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit
      DVA_LOG_LEVEL: debug
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: rabbitmq:4-management-alpine
    ports: [9080:15672]
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 15s
      timeout: 30s
      retries: 3

  callback-dummy:
    image: kennethreitz/httpbin
