openapi: 3.0.3


info:
  title: Data Veracity Assurance
  description: |-
    This is the API specification of the
    [data veracity assurance building block (DVA)](https://github.com/Prometheus-X-association/data-veracity).
  contact:
    email: bpeter@edu.bme.hu
  version: 0.1.0


servers:
  - url: http://localhost:1234/api


tags:
  - name: AoV
    description: Endpoints related to attestations of veracity (AoVs)
  - name: PoV
    description: Endpoints related to proofs of veracity (PoVs)
  - name: Verification
    description: Endpoints related to the verification of data veracity **(not of PoVs!)**


paths:

  /attestation:
    post:
      tags: [AoV]
      summary: Generate an AoV
      operationId: createAov
      requestBody:
        $ref: '#/components/requestBodies/VeracityRequest'
      responses:
        '200':
          description: Successfully generated AoV
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aov'  
        '400':
          description: Attestation denied
        '422':
          description: Validation exception

  /proof:
    post:
      tags: [PoV]
      summary: Generate a PoV
      operationId: createPov
      requestBody:
        $ref: '#/components/requestBodies/VeracityRequest'
      responses:
        '200':
          description: Successfully generated PoV
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pov'  
        '400':
          description: Proof generation denied
        '422':
          description: Validation exception


components:

  schemas:
    Aov:
      type: object
      properties:
        contractId:
          type: string
        dataPointer:
          type: string
        attesterId:
          type: string
        timestamp:
          type: string
          format: date-time
    Pov:
      type: object
      properties:
        contractId:
          type: string
        dataPointer:
          type: string
        proverId:
          type: string
        timestamp:
          type: string
          format: date-time
        proof:
          type: object

  requestBodies:
    VeracityRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              contractId:
                type: string
              dataPointer:
                type: string
