---
services:

  dva-jvm:
    build:
      context: ../
      dockerfile: ./dva-jvm/Dockerfile
    init: true
    healthcheck:
      test: nc -z localhost 9090
      interval: 5s
      timeout: 5s
      retries: 3

  dva-python:
    build:
      context: ../
      dockerfile: ./dva-python/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit

  rabbit:
    image: rabbitmq:4-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:8.0.9
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: >
        echo 'db.runCommand("ping").ok'
        | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5

  callback-dummy:
    build: callback-dummy/
    healthcheck:
      test: node healthcheck.js
      interval: 5s
      timeout: 5s
      retries: 3

  karate:
    build: karate/
    volumes:
      - ./karate-features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./karate-reports:/app/target/karate-reports
    command: ./features/

  aca-py:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6

  dva-aca-py-controller:
    build:
      context: ../
      dockerfile: ./dva-acapy-controller/Dockerfile
    init: true
    healthcheck:
      test: nc -z localhost 8050
      interval: 5s
      timeout: 5s
      retries: 3
