---
services:
  dva-api:
    build:
      context: ../
      dockerfile: ./dva-api/Dockerfile
  dva-processing:
    build:
      context: ../
      dockerfile: ./dva-processing/Dockerfile
    init: true
  rabbit:
    image: rabbitmq:4-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3
  mongo:
    image: mongo:8.0.9
    healthcheck:
      test: >
        echo 'db.runCommand("ping").ok'
        | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: dva
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
  karate:
    build: karate/
    volumes:
      - ./karate-features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./karate-reports:/app/target/karate-reports
      - ./karate-configs:/app/classpath:ro
      - ./karate-logs:/app/target/karate-logs
    command: ./features/
  aca-py:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6
  dva-aca-py-controller:
    build:
      context: ../
      dockerfile: ./dva-acapy-controller/Dockerfile
    init: true
    healthcheck:
      test: nc -z localhost 8050
      interval: 5s
      timeout: 5s
      retries: 3
  dva-dashboard-backend:
    build: ../dva-dashboard/backend/
  dva-dashboard-frontend:
    build: ../dva-dashboard/frontend/
  vla-manager-frontend:
    build: ../vla-manager/frontend/
