---
services:
  dva-api:
    build:
      context: ../
      dockerfile: ./dva-api/Dockerfile
  dva-processing:
    build:
      context: ../
      dockerfile: ./dva-processing/Dockerfile
    init: true
  vla-manager-api:
    build:
      context: ../
      dockerfile: ./vla-manager-api/Dockerfile
  dva-vc-manager:
    build:
      context: ../
      dockerfile: ./dva-vc-manager/Dockerfile
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: dva
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
  karate:
    build: karate/
    volumes:
      - ./karate-features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./karate-reports:/app/target/karate-reports
      - ./karate-configs:/app/classpath:ro
      - ./karate-logs:/app/target/karate-logs
    command: ./features/
  dva-dashboard:
    build: ../dva-dashboard/
  vla-manager:
    build: ../vla-manager/
