---
services:

  dva-jvm:
    build:
      context: ../
      dockerfile: ./dva-jvm/Dockerfile
    init: true
    healthcheck:
      test: nc -z localhost 9090
      interval: 5s
      timeout: 5s
      retries: 3

  dva-python:
    build:
      context: ../
      dockerfile: ./dva-python/Dockerfile
    init: true

  rabbit:
    image: rabbitmq:4-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  callback-dummy:
    build: callback-dummy/
    healthcheck:
      test: node healthcheck.js
      interval: 5s
      timeout: 5s
      retries: 3

  karate:
    build: karate/
    volumes:
      - ./karate-features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./karate-reports:/app/target/karate-reports
    command: ./features/
    depends_on:
      dva-api:
        condition: service_healthy
      callback-dummy:
        condition: service_healthy

  aca-py:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6

  dva-aca-py-controller:
    build:
      context: ../
      dockerfile: ./dva-acapy-controller/Dockerfile
    init: true
    healthcheck:
      test: nc -z localhost 8050
      interval: 5s
      timeout: 5s
      retries: 3
