---
services:

  dva-jvm:
    build:
      context: ../
      dockerfile: ./dva-jvm/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit
    healthcheck:
      test: nc -z localhost 9090
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      rabbit:
        condition: service_healthy
      mongo:
        condition: service_healthy

  dva-python:
    build:
      context: ../
      dockerfile: ./dva-python/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit
    depends_on:
      rabbit:
        condition: service_healthy
      mongo:
        condition: service_healthy

  rabbit:
    image: rabbitmq:4-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:8.0.9
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: >
        echo 'db.runCommand("ping").ok'
        | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5

  callback-dummy:
    build: callback-dummy/
    healthcheck:
      test: node healthcheck.js
      interval: 5s
      timeout: 5s
      retries: 3


  dashboard-backend:
    build:
      context: ../../dashboard-backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/dva
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000

  karate:
    build: karate/
    volumes:
      - ./karate-features:/app/features:ro
      - ./test-data:/app/test-data:ro
      - ./karate-reports:/app/target/karate-reports
    command: ./features/
    depends_on:
      dva-api:
        condition: service_healthy
      callback-dummy:
        condition: service_healthy
