---
services:

  dva-jvm:
    build:
      context: ../
      dockerfile: ./dva-jvm/Dockerfile
    init: true
    depends_on:
      rabbit:
        condition: service_healthy

  dva-python:
    build:
      context: ../
      dockerfile: ./dva-python/Dockerfile
    init: true
    environment:
      DVA_RABBITMQ_HOST: rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: rabbitmq:4-management-alpine
    ports: [9080:15672]
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 15s
      timeout: 30s
      retries: 3
