---
services:

  dva-mongo:
    extends:
      file: common-services.yml
      service: dva-mongo
    ports: [27017:27017]

  dva-api:
    extends:
      file: common-services.yml
      service: dva-jvm
    command: api
    ports: [9090:9090]

  # dva-processing-java:
  #   extends:
  #     file: common-services.yml
  #     service: dva-jvm
  #   command: processing

  dva-processing-python:
    extends:
      file: common-services.yml
      service: dva-python
    environment:
      DVA_LOG_LEVEL: debug
    develop:
      watch:
        - action: sync
          path: ../dva-python/
          target: /app/
          ignore: [.venv/]
        - action: rebuild
          path: ./pyproject.toml

  rabbit:
    extends:
      file: common-services.yml
      service: rabbit

  callback-dummy:
    profiles: [dev, karate]
    extends:
      file: common-services.yml
      service: callback-dummy
    ports: [9099:80]

  karate:
    profiles: [karate]
    extends:
      file: common-services.yml
      service: karate
