---
services:

  dva-api:
    extends:
      file: common-services.yml
      service: dva-jvm
    command: api
    ports: [9090:9090]

  # dva-processing-java:
  #   extends:
  #     file: common-services.yml
  #     service: dva-jvm
  #   command: processing

  dva-processing-python:
    extends:
      file: common-services.yml
      service: dva-python
    environment:
      DVA_LOG_LEVEL: debug
    develop:
      watch:
        - action: sync
          path: ../dva-python/
          target: /app/
          ignore: [.venv/]
        - action: rebuild
          path: ./pyproject.toml

  rabbit:
    extends:
      file: common-services.yml
      service: rabbit

  mongo:
    extends:
      file: common-services.yml
      service: mongo
    ports: [27017:27017]

  callback-dummy:
    profiles: [dev, karate]
    extends:
      file: common-services.yml
      service: callback-dummy
    ports: [9099:80]

  karate:
    profiles: [karate]
    extends:
      file: common-services.yml
      service: karate

  dashboard-backend:
    build:
      context: ../dashboard-backend
      dockerfile: Dockerfile
    environment:
      # Reuse the same Mongo service and DB name 'dva'
      MONGO_URL: mongodb://mongo:27017/dva
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
