---
name: Build and Test DVA API


on:
  push:
    paths: [dva-api/**]
  pull_request:
    paths: [dva-api/**]


defaults:
  run:
    working-directory: ./dva-api


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and test with Gradle
        working-directory: ./dva-api
        run: ./gradlew build
