---
name: Build and Test DVA Processing


on:
  push:
    paths:
      - dva-processing/src/**
      - dva-processing/tests/**
      - dva-processing/pyproject.toml
      - dva-processing/uv.lock
      - .github/workflows/build-dva-processing.yml
  pull_request:
    paths:
      - dva-processing/src/**
      - dva-processing/tests/**
      - dva-processing/pyproject.toml
      - dva-processing/uv.lock
      - .github/workflows/build-dva-processing.yml


permissions:
  contents: read


defaults:
  run:
    working-directory: ./dva-processing


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          working-directory: ./dva-processing
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync
      - name: Run Pytest
        run: uv run pytest
