name: Build and Test DVA Processing

on:
  push:
    paths:
      - 'dva-processing/**'
  pull_request:
    paths:
      - 'dva-processing/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install project dependencies
        working-directory: ./dva-processing
        run: uv sync

      - name: Run Pytest
        working-directory: ./dva-processing
        run: uv run pytest