name: Run Karate Tests

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Karate Integration Tests
        working-directory: ./test-env
        run: docker compose --profile karate up --build --abort-on-container-exit --exit-code-from karate